name: Hello World Code

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: print Hello World
        run: echo "Hello World"
